=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-core/zerocouplage-api/src/main/java/ressources/zcouplage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified"  >


<!-- Partie declaration  des  element -->

       <xs:complexType  name="valType">
              <xs:attribute name="ref-val" />
       </xs:complexType>
       
               
       <xs:complexType  name="bean-refType">
              <xs:attribute name="ref-bean" />
       </xs:complexType>
       
       <xs:complexType name="virtualViewType">
		<xs:attribute name="context" type="xs:string" use="required" />
		<xs:attribute name="class" type="xs:string" use="required" />
	  </xs:complexType>
       
       
       
       
    <xs:complexType  name="vueType">
    
    
     <xs:attribute    name="id-view"     type="xs:string"      use="required"  />
     <xs:attribute     name="target"     type="xs:string"      use="required"/>
     <xs:attribute  name="method"        type="xs:string"      use="optional"  /> 
     <xs:attribute  name="method-error"  type="xs:string"      use="optional"   />
    
    </xs:complexType>

      <xs:complexType    name="package-vueType"  >
          <xs:sequence>
             <xs:element  name="view"   type="vueType"   maxOccurs="unbounded" /> 
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="package-virtualViewType">
		<xs:sequence>
			<xs:element name="virtualView" type="virtualViewType" />
		</xs:sequence>
	</xs:complexType>
   
   
     <xs:complexType    name="keyType">
     
          <xs:attribute       name="bean-property"        type="xs:string"           use="required"/>   
          <xs:attribute       name="view-property"           type="xs:string"  use="required"  />  
          <xs:attribute       name="format" type="xs:string"  use="optional"/> 
     
     </xs:complexType>
   
   
   
   <xs:complexType   name="mappingType">
          <xs:sequence>
                <xs:element    name="key"   type="keyType"  minOccurs="1" maxOccurs="unbounded"     />
          </xs:sequence>
          
    <xs:attribute    name="ref-bean"   type="xs:string"   />
    <xs:attribute    name="ref-view"    type="xs:string"  />   
   </xs:complexType>
   <xs:complexType  name="mappingsType">
      <xs:sequence>
        <xs:element  name="mapping"   type="mappingType"   minOccurs="1"    maxOccurs="unbounded"/>   
     </xs:sequence>   
   </xs:complexType>

 
    
    
     <xs:complexType    name="BeanType" >
           <xs:attributeGroup  ref="attribute-beans" />
     </xs:complexType>

     <xs:complexType  name="package-beanType" >
        <xs:sequence>
		   <xs:element  name="bean" type="BeanType"   minOccurs="1"  maxOccurs="unbounded"  />
        </xs:sequence>
     </xs:complexType>

     <xs:complexType   name="package-buinessType"  >
          <xs:sequence>
             <xs:element  name="business"  type="buinessType"  minOccurs="1" maxOccurs="unbounded"  />
          </xs:sequence>
    </xs:complexType>



     <xs:complexType name="view-resultType">
          <xs:attribute  name="ref-view"  type="xs:string"     />
          <xs:attribute  name="name"   type="xs:string"        />
		  <xs:attribute  name="bean-result"   type="xs:string" />
      </xs:complexType>

  <xs:complexType   name="view-resultsType">
  <xs:sequence>
   <xs:element name="view-result" type="view-resultType"  minOccurs="1"   maxOccurs="unbounded"  />
  </xs:sequence>
  </xs:complexType>


     <xs:complexType name="validatorType">
        <xs:attribute  name="id-val" type="xs:string"     use="required"/>
        <xs:attribute    name="value"    type="xs:string"      use="required" />
        <xs:attribute   name="type-val"  type="xs:string"      use="required" />
    </xs:complexType>

     <xs:complexType name="package-validatorsType">
       <xs:sequence>
        <xs:element  name="validator"  type="validatorType"  minOccurs="1"  maxOccurs="unbounded"  />
       </xs:sequence>
    </xs:complexType>


    <xs:complexType name="buinessType"  >
       <xs:sequence>
           <xs:element  name="bean-ref" type="bean-refType" /> 
           <xs:element  name="validator-ref"  type="valType"  maxOccurs="unbounded" /> 
           <xs:element  name="view-results"   type="view-resultsType" minOccurs="1"  />
       </xs:sequence>
   <xs:attributeGroup    ref="attribute-buiness" /> 
     </xs:complexType>









<!-- declaration des  groupes d'attributs -->


<xs:attributeGroup  name="attribute-beans">

   <xs:attribute name="id-bean" type="xs:string" use="required" />
   <xs:attribute  name="class" type="xs:string" use="required" />

</xs:attributeGroup>

  <xs:attributeGroup name="attribute-buiness">
  <xs:attribute name="name"     type="xs:string"  use="required" />
  <xs:attribute name="class"    type="xs:string"  use="optional" />
  <xs:attribute name="method"    type="xs:string"  use="optional" />
   <xs:attribute name="pageError"    type="xs:string"  use="optional" />
 </xs:attributeGroup>

<!-- partie   declaration du fichier zcouplage.xml -->




<xs:complexType   name="zcouplageType"  >

  
    <xs:sequence>
    <xs:element name="virtualviews-package" type="package-virtualViewType" />
    <xs:element   name="mapping-view-bean"    type="mappingsType"   />
    <xs:element   name="package-validators"  type="package-validatorsType"   />
    <xs:element   name="beans-package"   type="package-beanType"  minOccurs="1"  /> 
    <xs:element   name="business-package" type="package-buinessType"  minOccurs="1" />
    <xs:element   name="views-package"       type="package-vueType"  />
    </xs:sequence>
 <xs:attribute  name="context" >
  
  <xs:simpleType>
     <xs:restriction   base="xs:string" >
         <xs:enumeration   value="Web" />
         <xs:enumeration   value="Desktop" />
     </xs:restriction>
     </xs:simpleType>
 </xs:attribute>
 
 <xs:attribute  name="DevModes">
  <xs:simpleType>
      <xs:restriction   base="xs:string">
      
        <xs:enumeration   value="prod"   /> 
        <xs:enumeration   value="Dev"    />   
      </xs:restriction>
      </xs:simpleType>  
 </xs:attribute>
 
 </xs:complexType>
  
<xs:element   name="xml"  >
  <xs:complexType>
    <xs:sequence>
     <xs:element name="zcouplage"   type="zcouplageType"     />
    </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-web/zerocouplage-test-web/src/main/resources/zerocouplage.xml
<?xml version="1.0"?>
<!--   xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcouplage.xsd"> -->
<zcouplage
    DevModes="prod"
    context="web" >
     <virtualviews-package>

		<virtualview class="org.zerocouplage.web.manager.ZCManagerWeb"
			context="web" />
	</virtualviews-package>

    <!-- mapping   package -->

    <mapping-view-bean>

        <mapping
            isSame="false"
            ref-bean="UserBeanIn"
            ref-view="viewI" >

            <key
                beanProperty="nom"
                viewProperty="firstName" />

            <key
                beanProperty="prenom"
                viewProperty="lastName" />
            <key
                beanProperty="age"
                viewProperty="ageout" />
            
            <key
                beanProperty="dateanniversaire"
                viewProperty="birthday" format="dd/MM/yyyy"/>
            
               <key
                beanProperty="taille"
                viewProperty="tail" />
 <key
                beanProperty="question"
                viewProperty="questionout" />
  <key
                beanProperty="file"
                viewProperty="fil" /> 
               
        </mapping>
    </mapping-view-bean>
    

    <!-- validators package -->

    <validators-package>

        <validator name="valForm"  typeVal="file" valueTarget="ZC_val.xml" />
        <validator name="val" typeVal="file" valueTarget="validate.xml" />
            <validator name="validator" typeVal="class" valueTarget="org.zerocouplage.test.web.validateClass.ValidateForm" />
    </validators-package>

    <!-- beans-package -->

    <beans-package>

        <bean
            name="UserBeanIn"
            class="org.zerocouplage.test.web.bean.userBeanIn" />
    </beans-package>

    <!-- Business   package -->

    <business-package>

        <business
            name="processing"
            class="org.zerocouplage.test.web.action.ProcessForm"
            method="process" 
            pageError="error"
            >

            <bean-ref ref-bean="UserBeanIn" />

            <validators-refs>
				<validator-ref ref-val="valForm" />
				<validator-ref ref-val="val" />
				<validator-ref ref-val="validator"/>
			</validators-refs>

            <view-results>

                <view-result
                    name="success"
                    bean-result="out"
                    ref-view="viewR" />
                
            </view-results>
        </business>
    </business-package>

    <!-- Views   package -->

    <views-package>

        <view
            name="viewR"
            method=""
            methodError=""
            target="hello.jsp" />

        <view
            name="viewI"
            method=""
            methodError=""
            target="index.jsp" />
        <view
            name="error"
            method=""
            methodError=""
            target="error.jsp" />
    </views-package>

    <!-- Add  packages  here -->

</zcouplage>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-core/zerocouplage-impl/ressources/zerocouplage.xml
<xml  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcouplage.xsd"  >
<zcouplage     context="Web"     DevModes="prod" >
      
              
 <!--  mapping   package  -->  
   <mapping-view-bean>
       <mapping    isSame="false"    ref-bean="Beanin"    ref-view="Viewin"  >
            <key    beanProperty="fistname"     viewProperty="login"        />
            <key    beanProperty="lastname"     viewProperty="password"        />
        </mapping>
       
 </mapping-view-bean>     
            
     
 <!--validators package -->      
    <validators-package>
         <validator   name="valForm1"    valueTarget="valider.xml"    typeVal="file"      />
         <validator   name="valForm2"    valueTarget="org.zerocouplage.valider"  typeVal="class"      />
  </validators-package>
  
   
 <!--beans-package -->
    <beans-package>
       <bean   name="beanin"     class="beanoutput.java" />
     
       
   </beans-package>

  

  <!-- Business   package--> 
  <business-package >
     
       <business name="proc1"   class="zerocouplage.test.web.ProcessForm"    method="process" >
            
            <bean-ref       ref-bean="beanin" />
            <validator-ref  ref-val="valForm" />
            <view-results>   
		        <view-result    ref-view="viewR"     name="succes"  bean-result="beanresult" />
            </view-results>
       
       </business>     
       <business name="proc2"   class="zerocouplage.test.web.ProcessForm2"    method="process2" >
            
            <bean-ref       ref-bean="beanin" />
            <validator-ref  ref-val="valForm1" />
            <view-results>   
		        <view-result    ref-view="viewR"     name="succes"  bean-result="beanresult" />
            </view-results>
       
       </business>  
     
  </business-package> 


<!-- Views   package -->
    <views-package>
        <view name="viewR"   target="validate1.jsp"  method="1"   methodError="processError1"  />
        <view name="view2"   target="validate2.jsp"  method="2"   methodError="processError2"  />
        <view name="view3"   target="validate3.jsp"  method="3"   methodError="processError3"  />
    </views-package>

<!-- Add  packages  here-->


</zcouplage>

</xml>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-web/zerocouplage-test-web/ressources/zerocouplage.xml
<?xml version="1.0"?>
<!--   xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcouplage.xsd"> -->
<zcouplage
    DevModes="prod"
    context="web" >

    <!-- mapping   package -->

    <mapping-view-bean>

        <mapping
            isSame="false"
            ref-bean="UserBeanIn"
            ref-view="viewI" >

            <key
                beanProperty="nom"
                viewProperty="firstName" />

            <key
                beanProperty="prenom"
                viewProperty="lastName" />
        </mapping>
    </mapping-view-bean>

    <!-- validators package -->

    <validators-package>

        <validator
            name="valForm"
            typeVal="file"
            valueTarget="ZC_val.xml" />
    </validators-package>

    <!-- beans-package -->

    <beans-package>

        <bean
            name="UserBeanIn"
            class="org.zerocouplage.test.web.bean.userBeanIn" />
    </beans-package>

    <!-- Business   package -->

    <business-package>

        <business
            name="processing"
            class="org.zerocouplage.test.web.action.ProcessForm"
            method="process" >

            <bean-ref ref-bean="UserBeanIn" />

            <validator-ref ref-val="valForm" />

            <view-results>

                <view-result
                    name="success"
                    bean-result="out"
                    ref-view="viewR" />
            </view-results>
        </business>
    </business-package>

    <!-- Views   package -->

    <views-package>

        <view
            name="viewR"
            method=""
            methodError=""
            target="hello.jsp" />

        <view
            name="viewI"
            method="createGui"
            methodError="processError"
            target="org.zerocouplage.test.desktop.view.UserView" />
    </views-package>

    <!-- Add  packages  here -->

</zcouplage>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-application/zerocouplage-application-desktop/src/main/java/ressources/zerocouplage.xml
<?xml version="1.0" encoding="UTF-8"?>
<zcouplage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="zcouplage.xsd" DevModes="prod" context="desktop">
	<virtualviews-package>
		<virtualview class="org.zerocouplage.desktop.manager.ZCVirtualDesktop"
			context="desktop" />
	</virtualviews-package>

	<!-- Mapping package -->

	<mapping-view-bean>

		<mapping isSame="false" ref-bean="BeanUser" ref-view="viewFormCandidature">
			<key beanProperty="nom" viewProperty="firstName" />
			<key beanProperty="prenom" viewProperty="lastName" />
			<key beanProperty="dan" viewProperty="birthday" format="dd/MM/yyyy" />
			<key beanProperty="email" viewProperty="mail" />
			<key beanProperty="civilite" viewProperty="civilite" />
			<key beanProperty="nbAnneeExp" viewProperty="nbAnneeExp" />
			<key beanProperty="natureDemande" viewProperty="natureDemande" />
			<key beanProperty="Cv" viewProperty="cv" />
		</mapping>

		<mapping isSame="false" ref-bean="AdminBeanIn" ref-view="viewAuthentification">
			<key beanProperty="login_admin" viewProperty="login" />
			<key beanProperty="password_admin" viewProperty="password" />
		</mapping>

		<mapping isSame="false" ref-bean="BeanUser" ref-view="view5">
			<key beanProperty="idUser" viewProperty="idCandidat" />
			<key beanProperty="path" viewProperty="pathCv" />
		</mapping>

	</mapping-view-bean>

	<!-- Validators package -->
	<validators-package>
		<validator name="val1" typeVal="file" valueTarget="Recrut_val.xml" />
		<validator name="val2" typeVal="class"
			valueTarget="org.zerocouplage.application.desktop.validateClass.RecrutValidation" />
		<validator name="Adminvalidator" typeVal="class"
			valueTarget="org.zerocouplage.application.desktop.validateClass.AdminValidate" />
	</validators-package>

	<!-- Beans-package -->
	<beans-package>
		<bean name="BeanUser" class="org.zerocouplage.application.desktop.bean.BeanUser" />
		<bean name="AdminBeanIn"
			class="org.zerocouplage.application.desktop.bean.AdminBeanIn" />
		<bean name="PathBean" class="org.zerocouplage.application.desktop.bean.Path" />
	</beans-package>

	<!-- Business package -->
	<business-package>
		<business name="Formprocessing"
			class="org.zerocouplage.application.desktop.business.RecrutBusiness"
			method="Formprocess">
			<bean-ref ref-bean="BeanUser" />
			<validators-refs>
				<validator-ref ref-val="val1" />
				<validator-ref ref-val="val2" />
			</validators-refs>
			<view-results>
				<view-result name="success" bean-result="userout"
					ref-view="viewFormResult" />
			</view-results>
		</business>
		<business name="processingAcceuil">
			<view-results>
				<view-result ref-view="viewAccueil" />
			</view-results>
		</business>

		<business name="processingToFullDB">
			<bean-ref ref-bean="AdminBeanIn" />
			<validators-refs>
				<validator-ref ref-val="Adminvalidator" />
			</validators-refs>
			<view-results>
				<view-result ref-view="view7" />
			</view-results>
		</business>

		<business name="processingToForm">
			<view-results>
				<view-result name="success" ref-view="viewFormCandidature" />
			</view-results>
		</business>

		<business name="processingToAuthentification">
			<view-results>
				<view-result name="success" ref-view="viewAuthentification" />
			</view-results>
		</business>
		<business name="processingEmpty"
			class="org.zerocouplage.application.desktop.business.RecrutBusiness"
			method="processTODB">
			<bean-ref ref-bean="AdminBeanIn" />
			<validators-refs>
				<validator-ref ref-val="Adminvalidator" />
			</validators-refs>
			<view-results>
				<view-result name="success" bean-result="adminout"
					ref-view="viewEmptyBD" />
			</view-results>
		</business>

		<business name="showCv"
			class="org.zerocouplage.application.desktop.business.RecrutBusiness"
			method="openFile">
			<bean-ref ref-bean="BeanUser" />
			<view-results>
				<view-result name="success" bean-result="result"
					ref-view="File" />
			</view-results>
		</business>


		<business name="deleteCandidat"
			class="org.zerocouplage.application.desktop.business.RecrutBusiness"
			method="deleteCandidat">
			<bean-ref ref-bean="BeanUser" />
			<view-results>
				<view-result name="success" ref-view="view5" />
				<view-result name="failed" ref-view="view6" />
			</view-results>
		</business>

		<business name="return">
			<view-results>
				<view-result name="success" ref-view="view4" />
			</view-results>
		</business>
		<business name="bdVide">
			<view-results>
				<view-result name="success" ref-view="view6" />
			</view-results>
		</business>

	</business-package>

	<!-- Views package -->
	<views-package>

		<view name="viewFormCandidature" method="createGui" methodError="processError"
			target="org.zerocouplage.application.desktop.view.FormCandidature" />

		<view name="viewFormResult" method="createResultGui" methodError=""
			target="org.zerocouplage.application.desktop.view.FormResult" />

		<view name="viewAuthentification" method="createGui" methodError="processError"
			target="org.zerocouplage.application.desktop.view.Authentification" />

		<view name="viewAccueil" method="createGui"
			target="org.zerocouplage.application.desktop.view.Acceuil" />

		<view name="view5" method="chargertableau" methodError=""
			target="org.zerocouplage.application.desktop.view.DataAccess" />

		<view name="view7" method="creatGui" methodError=""
			target="org.zerocouplage.application.desktop.view.DataAccess" />

		<view name="view6" method="createGui" methodError=""
			target="org.zerocouplage.application.desktop.view.BdVide" />

		<view name="view4" method="createGui" methodError=""
			target="org.zerocouplage.application.desktop.view.Acceuil" />

		<view name="File" method="createGui" methodError=""
			target="org.zerocouplage.application.desktop.view.ShowFile" />
	</views-package>

</zcouplage>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-rolemanager/zerocouplage-rolemanager-test-web-1.0.0/ressources/zerocouplage.xml
<?xml version="1.0"?>
<!--   xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcouplage.xsd">
 -->
<zcouplage
    DevModes="prod"
    context="web" >
   
    <!-- mapping   package -->

    <mapping-view-bean>

        <mapping
            isSame="false"
            ref-bean="UserBeanIn"
            ref-view="viewI" >

            <key
                beanProperty="action"
                viewProperty="out_action" />
   
            <key
                beanProperty="prenom"
                viewProperty="lastname" />   
        </mapping>
    </mapping-view-bean>

    <!-- Security Role Manager Package -->
	<role-manager class="com.zerocouplage.test.web.bean.ZCRule">
		<policy name="securityPolicy"
				valueTarget="ressources/ZC_security.xml"
				errorPage="error.jsp"
				/>
				
	</role-manager>
	    
	<!-- validators package -->
    <validators-package>

        <validator
            name="valForm"
            typeVal="file"
            valueTarget="ressources/ZC_val.xml" />
    </validators-package>

    <!-- beans-package -->

    <beans-package>

        <bean
            name="UserBeanIn"
            class="com.zerocouplage.test.web.bean.userBeanIn" />
    </beans-package>

    <!-- Business   package -->

    <business-package>
		
        <business
            name="gnote_rectify"
            class="com.zerocouplage.test.web.action.GNote"
            method="rectify"  >

            <bean-ref ref-bean="UserBeanIn" />

            <validator-ref ref-val="valForm" />

            <view-results>

                <view-result
                    name="Rectify"
                    bean-result="out"
                    ref-view="viewR" />
                      
            </view-results>  
        </business>
        
        <business
            name="gnote_show"
            class="com.zerocouplage.test.web.action.GNote"
            method="show" >

            <bean-ref ref-bean="UserBeanIn" />

            <validator-ref ref-val="valForm" />

            <view-results>

                <view-result
                    name="Show"
                    bean-result="out"
                    ref-view="viewSh" /> 
                      
            </view-results>  
        </business>
        
        <business
            name="gnote_save"
            class="com.zerocouplage.test.web.action.GNote"
            method="save" >

            <bean-ref ref-bean="UserBeanIn" />

            <validator-ref ref-val="valForm" />

            <view-results>

                <view-result
                    name="Save"
                    bean-result="out"
                    ref-view="viewS" /> 
                      
            </view-results>  
        </business>
        
    </business-package>

    <!-- Views   package -->

    <views-package>

        <view
            name="viewR"
            method=""
            methodError=""
            target="rectify.jsp" />
            
        <view
            name="viewS"
            method=""
            methodError=""
            target="save.jsp" />

        <view
            name="viewSh"
            method=""
            methodError=""
            target="show.jsp" />
            
        <view
            name="viewI"
            method="createGui"
            methodError="processError"
            target="index.jsp" />
            
        <view
            name="viewError"
            method=""
            methodError="processError"
            target="error.jsp" />    
    </views-package>

    <!-- Add  packages  here -->

</zcouplage>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-desktop/zerocouplage-test-desktop/src/main/java/ressources/zerocouplage.xml
<?xml version="1.0" encoding="UTF-8"?>
<zcouplage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='zcouplage.xsd' DevModes="prod" context="desktop">

	<!-- virtualView package -->
	<virtualviews-package>
		<virtualView context="desktop"
			class="org.zerocouplage.desktop.manager.ZCVirtualDesktop" />
	</virtualviews-package>

	<!-- Mapping package -->
	<mapping-view-bean>
		<mapping isSame="false" ref-bean="UserBeanIn" ref-view="viewI">
			<key beanProperty="nom" viewProperty="firstName" />
			<key beanProperty="prenom" viewProperty="lastName" />
			<key beanProperty="dateNaissance" viewProperty="birthday" format="dd/MM/yyyy" />
			<key beanProperty="age" viewProperty="age" />
			<key beanProperty="taille" viewProperty="sizee" />
			<key beanProperty="question" viewProperty="question" />
			<key beanProperty="file" viewProperty="fil" />
			<key beanProperty="list" viewProperty="listToString" />
		</mapping>
	</mapping-view-bean>

	<!-- Validators package -->
	<validators-package>
		<validator name="valForm" typeVal="file" valueTarget="ZC_val.xml" />
		<validator name="val" typeVal="file" valueTarget="validate.xml" />
		<validator name="validator" typeVal="class"
			valueTarget="org.zerocouplage.test.desktop.validateClass.ValidateForm" />
	</validators-package>

	<!-- Beans-package -->
	<beans-package>
		<bean name="UserBeanIn" class="org.zerocouplage.test.desktop.bean.UserBeanIn" />
	</beans-package>


	<!-- Business package -->
	<business-package>
		<!-- <business name="processing" -->
		<!-- class="org.zerocouplage.test.desktop.business.ProcessForm1" method="process"> -->

		<!-- <view-results> -->
		<!-- <view-result name="success" ref-view="viewR1" /> -->
		<!-- </view-results> -->
		<!-- </business> -->

		<business name="processing"
			class="org.zerocouplage.test.desktop.business.ProcessForm" method="process"
			pageError="error">

			<bean-ref ref-bean="UserBeanIn" />

			<validators-refs>
				<validator-ref ref-val="valForm" />
				<validator-ref ref-val="validate" />
				<validator-ref ref-val="validator" />
			</validators-refs>

			<view-results>
				<view-result name="success" bean-result="out" ref-view="viewR" />
			</view-results>

		</business>

		<business name="processing2"
			class="org.zerocouplage.test.desktop.business.ProcessForm1" method="process">
			<bean-ref ref-bean="UserBeanIn" />
			<validators-refs>
				<validator-ref ref-val="valForm" />
				<validator-ref ref-val="validate" />
				<validator-ref ref-val="validator" />
			</validators-refs>
			<view-results>
				<view-result name="success" ref-view="view1" />
			</view-results>
		</business>
		<business name="processing3"
			class="org.zerocouplage.test.desktop.business.ProcessForm1" method="process2">
			<view-results>
				<view-result name="success" ref-view="viewI" />
			</view-results>
		</business>

<!-- 		<business name="processing3"> -->
<!-- 			<view-results> -->
<!-- 				<view-result name="success" ref-view="view2" /> -->
<!-- 			</view-results> -->
<!-- 		</business> -->

	</business-package>

	<!-- Views package -->
	<views-package>

		<view name="viewI" method="createGui" methodError="processError"
			target="org.zerocouplage.test.desktop.view.UserView" />

		<view name="viewR1" method="createResultGui" methodError=""
			target="org.zerocouplage.test.desktop.view.UserDisplayView1" />

		<view name="viewR" method="createResultGui" methodError=""
			target="org.zerocouplage.test.desktop.view.UserDisplayView" />

		<view name="view1" method="createGui" methodError=""
			target="org.zerocouplage.test.desktop.view.Redirect" />
		
		<view name="error" method="" methodError="displayError"
			target="org.zerocouplage.test.desktop.view.ErrorView" />

	</views-package>
</zcouplage>

=== BouazaBouzidi/Zerocouplage-framework/zc-demo-todo-mvc/src/main/resources/zerocouplage.xml
<?xml version="1.0"?>
<!-- xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcouplage.xsd"> -->





<zcouplage DevModes="dev" context="web" appName="todoMVC">
	
	<virtualviews-package>
		<virtualview class="org.zerocouplage.web.manager.ZCComponentVirtualWeb"
			context="web" />
		<virtualview class="org.zerocouplage.desktop.manager.ZCVirtualDesktop"
			context="desktop" />
		<virtualview class="org.zerocouplage.mobile.manager.ZCVirtualMobile"
			context="mobile" />
	</virtualviews-package>


	<!-- mapping package -->
	<mapping-view-bean>
		<mapping isSame="true" ref-bean="TodoBean" ref-view="Index" />
	</mapping-view-bean>


	<!-- validators package -->
	<validators-package />

	<!-- beans-package -->
	<beans-package>
		<bean name="TodoBean" class="org.zerocouplage.tutorial.todomvc.beans.TodoBean" />
	</beans-package>
	<!-- Business package -->

	<business-package>

		<business name="index">
			<view-results>
				<view-result ref-view="Index" />
			</view-results>
		</business>

		<business name="addNewTodo" class="org.zerocouplage.tutorial.todomvc.action.TodoHandler"
			method="addTodo">
			<bean-ref ref-bean="TodoBean" />
			<view-results>
				<view-result name="success" bean-result="allTodos"
					ref-view="todoMVCView" />
			</view-results>
		</business>
		
	</business-package>

	<!-- Views package -->
	<views-package>
		<view name="Index" method="display" methodError="processError"
			beanIn="" target="org.zerocouplage.tutorial.todomvc.views.Index" />
		<view name="todoMVCView" method="display" methodError="processError"
			beanIn="allTodos" target="org.zerocouplage.tutorial.todomvc.views.Index" />
	</views-package>
	
	<!-- Add packages here -->

</zcouplage>
