=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-core/zerocouplage-api/src/main/java/ressources/zcouplage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified"  >


<!-- Partie declaration  des  element -->

       <xs:complexType  name="valType">
              <xs:attribute name="ref-val" />
       </xs:complexType>
       
               
       <xs:complexType  name="bean-refType">
              <xs:attribute name="ref-bean" />
       </xs:complexType>
       
       <xs:complexType name="virtualViewType">
		<xs:attribute name="context" type="xs:string" use="required" />
		<xs:attribute name="class" type="xs:string" use="required" />
	  </xs:complexType>
       
       
       
       
    <xs:complexType  name="vueType">
    
    
     <xs:attribute    name="id-view"     type="xs:string"      use="required"  />
     <xs:attribute     name="target"     type="xs:string"      use="required"/>
     <xs:attribute  name="method"        type="xs:string"      use="optional"  /> 
     <xs:attribute  name="method-error"  type="xs:string"      use="optional"   />
    
    </xs:complexType>

      <xs:complexType    name="package-vueType"  >
          <xs:sequence>
             <xs:element  name="view"   type="vueType"   maxOccurs="unbounded" /> 
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="package-virtualViewType">
		<xs:sequence>
			<xs:element name="virtualView" type="virtualViewType" />
		</xs:sequence>
	</xs:complexType>
   
   
     <xs:complexType    name="keyType">
     
          <xs:attribute       name="bean-property"        type="xs:string"           use="required"/>   
          <xs:attribute       name="view-property"           type="xs:string"  use="required"  />  
          <xs:attribute       name="format" type="xs:string"  use="optional"/> 
     
     </xs:complexType>
   
   
   
   <xs:complexType   name="mappingType">
          <xs:sequence>
                <xs:element    name="key"   type="keyType"  minOccurs="1" maxOccurs="unbounded"     />
          </xs:sequence>
          
    <xs:attribute    name="ref-bean"   type="xs:string"   />
    <xs:attribute    name="ref-view"    type="xs:string"  />   
   </xs:complexType>
   <xs:complexType  name="mappingsType">
      <xs:sequence>
        <xs:element  name="mapping"   type="mappingType"   minOccurs="1"    maxOccurs="unbounded"/>   
     </xs:sequence>   
   </xs:complexType>

 
    
    
     <xs:complexType    name="BeanType" >
           <xs:attributeGroup  ref="attribute-beans" />
     </xs:complexType>

     <xs:complexType  name="package-beanType" >
        <xs:sequence>
		   <xs:element  name="bean" type="BeanType"   minOccurs="1"  maxOccurs="unbounded"  />
        </xs:sequence>
     </xs:complexType>

     <xs:complexType   name="package-buinessType"  >
          <xs:sequence>
             <xs:element  name="business"  type="buinessType"  minOccurs="1" maxOccurs="unbounded"  />
          </xs:sequence>
    </xs:complexType>



     <xs:complexType name="view-resultType">
          <xs:attribute  name="ref-view"  type="xs:string"     />
          <xs:attribute  name="name"   type="xs:string"        />
		  <xs:attribute  name="bean-result"   type="xs:string" />
      </xs:complexType>

  <xs:complexType   name="view-resultsType">
  <xs:sequence>
   <xs:element name="view-result" type="view-resultType"  minOccurs="1"   maxOccurs="unbounded"  />
  </xs:sequence>
  </xs:complexType>


     <xs:complexType name="validatorType">
        <xs:attribute  name="id-val" type="xs:string"     use="required"/>
        <xs:attribute    name="value"    type="xs:string"      use="required" />
        <xs:attribute   name="type-val"  type="xs:string"      use="required" />
    </xs:complexType>

     <xs:complexType name="package-validatorsType">
       <xs:sequence>
        <xs:element  name="validator"  type="validatorType"  minOccurs="1"  maxOccurs="unbounded"  />
       </xs:sequence>
    </xs:complexType>


    <xs:complexType name="buinessType"  >
       <xs:sequence>
           <xs:element  name="bean-ref" type="bean-refType" /> 
           <xs:element  name="validator-ref"  type="valType"  maxOccurs="unbounded" /> 
           <xs:element  name="view-results"   type="view-resultsType" minOccurs="1"  />
       </xs:sequence>
   <xs:attributeGroup    ref="attribute-buiness" /> 
     </xs:complexType>









<!-- declaration des  groupes d'attributs -->


<xs:attributeGroup  name="attribute-beans">

   <xs:attribute name="id-bean" type="xs:string" use="required" />
   <xs:attribute  name="class" type="xs:string" use="required" />

</xs:attributeGroup>

  <xs:attributeGroup name="attribute-buiness">
  <xs:attribute name="name"     type="xs:string"  use="required" />
  <xs:attribute name="class"    type="xs:string"  use="optional" />
  <xs:attribute name="method"    type="xs:string"  use="optional" />
   <xs:attribute name="pageError"    type="xs:string"  use="optional" />
 </xs:attributeGroup>

<!-- partie   declaration du fichier zcouplage.xml -->




<xs:complexType   name="zcouplageType"  >

  
    <xs:sequence>
    <xs:element name="virtualviews-package" type="package-virtualViewType" />
    <xs:element   name="mapping-view-bean"    type="mappingsType"   />
    <xs:element   name="package-validators"  type="package-validatorsType"   />
    <xs:element   name="beans-package"   type="package-beanType"  minOccurs="1"  /> 
    <xs:element   name="business-package" type="package-buinessType"  minOccurs="1" />
    <xs:element   name="views-package"       type="package-vueType"  />
    </xs:sequence>
 <xs:attribute  name="context" >
  
  <xs:simpleType>
     <xs:restriction   base="xs:string" >
         <xs:enumeration   value="Web" />
         <xs:enumeration   value="Desktop" />
     </xs:restriction>
     </xs:simpleType>
 </xs:attribute>
 
 <xs:attribute  name="DevModes">
  <xs:simpleType>
      <xs:restriction   base="xs:string">
      
        <xs:enumeration   value="prod"   /> 
        <xs:enumeration   value="Dev"    />   
      </xs:restriction>
      </xs:simpleType>  
 </xs:attribute>
 
 </xs:complexType>
  
<xs:element   name="xml"  >
  <xs:complexType>
    <xs:sequence>
     <xs:element name="zcouplage"   type="zcouplageType"     />
    </xs:sequence>
   </xs:complexType>
</xs:element>
</xs:schema>

=== BouazaBouzidi/Zerocouplage-framework/zerocouplage-application/zerocouplage-application-web/src/main/java/ressources/zerocouplage.xml
<?xml version="1.0"?>
<!-- xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zcouplage.xsd"> -->
<zcouplage DevModes="prod" context="web">


	<!-- mapping package -->

	<mapping-view-bean>

		<mapping isSame="false" ref-bean="BeanUser" ref-view="viewFormCandidature">
			<key beanProperty="nom" viewProperty="firstName" />
			<key beanProperty="prenom" viewProperty="lastName" />
			<key beanProperty="dan" viewProperty="birthday" format="dd/MM/yyyy" />
			<key beanProperty="email" viewProperty="mail" />
			<key beanProperty="civilite" viewProperty="civilite" />
			<key beanProperty="nbAnneeExp" viewProperty="nbAnneeExp" />
			<key beanProperty="natureDemande" viewProperty="natureDemande" />
			<key beanProperty="Cv" viewProperty="cv" />
		</mapping>
		
		<mapping isSame="false" ref-bean="AdminBeanIn" ref-view="viewI">
			<key beanProperty="login_admin" viewProperty="login" />
			<key beanProperty="password_admin" viewProperty="pass" />
		</mapping>

		<mapping isSame="false" ref-bean="BeanUser" ref-view="Data">
		    <key beanProperty="idUser" viewProperty="idCandidat" />
			<key beanProperty="path" viewProperty="pathCv" />
		</mapping>

	</mapping-view-bean>

	<!-- validators package -->

	<validators-package>
		<validator name="val1" typeVal="file" valueTarget="Recrut_val.xml" />
		<validator name="val2" typeVal="class"
			valueTarget="org.zerocouplage.application.web.validateClass.RecrutValidation" />
		<validator name="Adminvalidator" typeVal="class"
			valueTarget="org.zerocouplage.application.web.validateClass.AdminValidate" />
	</validators-package>

	<!-- beans-package -->

	<beans-package>
		<bean name="AdminBeanIn" class="org.zerocouplage.application.web.bean.AdminBeanIn" />
		<bean name="UserBeanIn" class="org.zerocouplage.application.web.bean.userBeanIn" />
		<bean name="BeanUser" class="org.zerocouplage.application.web.bean.BeanUser" />
	</beans-package>

	<!-- Business package -->

	<business-package>

		<business name="processing"
			class="org.zerocouplage.application.web.business.RecrutBusiness"
			method="process1">
			<bean-ref ref-bean="AdminBeanIn" />
			<validators-refs>
<!-- 				<validator-ref ref-val="Adminvalidator" /> -->
			</validators-refs>
			<view-results>
				<view-result name="success" bean-result="outt" ref-view="Data" />
			</view-results>
		</business>
		<business name="showData"
			class="org.zerocouplage.application.web.business.RecrutBusiness"
			method="getData">
			<view-results>
				<view-result name="success" ref-view="Data" />
			</view-results>
		</business>

		<business name="showCv"
			class="org.zerocouplage.application.web.business.RecrutBusiness"
			method="openFile">
			<bean-ref ref-bean="BeanUser" />
			<view-results>
				<view-result name="success" bean-result="fileResult"
					ref-view="test" />
			</view-results>
		</business>

		<business name="deleteCandidat"
			class="org.zerocouplage.application.web.business.RecrutBusiness"
			method="deleteCandidat">
			<bean-ref ref-bean="BeanUser" />
			<view-results>
				<view-result name="success" ref-view="Data" />
				<view-result name="error" ref-view="viewEmptyBD" />
			</view-results>
		</business>

		<business name="return">
			<view-results>
				<view-result name="success" ref-view="viewAccueil" />
			</view-results>
		</business>
		<business name="bdVide">
			<view-results>
				<view-result name="success" ref-view="emptyBd" />
			</view-results>
		</business>
		<business name="Formprocessing"
			class="org.zerocouplage.application.web.business.RecrutBusiness" method="Formprocess">
			<bean-ref ref-bean="BeanUser" />
			<validators-refs>
				<validator-ref ref-val="val1" />
				<validator-ref ref-val="val2" />
			</validators-refs>
			<view-results>
				<view-result name="success" bean-result="userout"
					ref-view="viewFormResult" />
			</view-results>
		</business>

		<business name="return">
			<view-results>
				<view-result ref-view="viewAccueil" />
			</view-results>
		</business>

		<business name="processingformulaire">
			<view-results>
				<view-result ref-view="viewFormCandidature" />
			</view-results>
		</business>

		<business name="processingcandidat">
			<view-results>
				<view-result ref-view="viewI" />
			</view-results>
		</business>

	</business-package>

	<!-- Views package -->

	<views-package>

		<view name="viewR" method="" methodError="" target="adminResult.jsp" />

		<view name="viewI" method="" methodError="" target="admin.jsp" />

		<view name="returnn" method="" methodError="" target="formulaire.jsp" />

		<view name="viewAccueil" method="" target="Accueil.jsp" />

		<view name="Data" method="" methodError="" target="DataAccess.jsp" />

		<view name="File" method="" methodError="" target="ShowFile.jsp" />

		<view name="emptyBd" method="" methodError="" target="EmptyBD.jsp" />

		<view name="viewFormCandidature" method="" methodError=""
			target="FormCandidature.jsp" />

		<view name="viewFormResult" method="" methodError=""
			target="FormResult.jsp" />

		<view name="viewAccueil" method="" methodError="" target="Accueil.jsp" />

		<view name="test" method="" methodError="" target="test.jsp" />

	</views-package>

	<!-- Add packages here -->

</zcouplage>
